# Perceptrons and Multi-Layer Perceptrons

* Neurons are the basic structure that form a neural network. A neuron receives an input, that is represented by a value, applies a linear transformation on this input, applies an activation function on the transformation result and retrieves a single output;
* Perceptrons are single layer neural networks that work as a linear classifier (binary classifier). They can have several neurons on its composition, but just in the same layer.

### Simple pytorch model intuition

In [1]:
import torch

In [2]:
class Model():
    # constructor
    def __init__(self, num_inputs):
        # w -> sampled from a normal distribution with mean 0 and standard deviation 1
        self.w = torch.normal(mean=0,std=1,size=(num_inputs,1), requires_grad=True)
        # b -> constant value (1 or 0) or even 1/total number of classes
        self.b = torch.zeros(1, requires_grad=True) 

    # foward -> processes an input X value through the output
    def foward(self, X):
        return X@self.w + self.b

    # quadratic loss
    def loss(self, y, y_hat):
        l = (y_hat - y.reshape(y_hat.shape))**2/2
        return l.mean()

In [3]:
my_model = Model(2)

In [4]:
my_model.w, my_model.b

(tensor([[-1.2474],
         [-0.4756]], requires_grad=True),
 tensor([0.], requires_grad=True))

In [5]:
my_model.foward(torch.tensor([1,1],  dtype=torch.float32))

tensor([-1.7230], grad_fn=<AddBackward0>)

In [6]:
# Regression
X = torch.arange(16,dtype=torch.float32).reshape([8,2]) + torch.normal(mean=0,std=.5,size=(8,2))
y = torch.arange(8, dtype=torch.float32)

X,y

(tensor([[ 0.1726,  0.0313],
         [ 2.6660,  3.6804],
         [ 3.4600,  6.1613],
         [ 6.2355,  6.4295],
         [ 9.2588,  9.8744],
         [10.3935, 10.5823],
         [13.3872, 13.2554],
         [13.7307, 14.7170]]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7.]))

In [7]:
my_model.foward(X), y

(tensor([[ -0.2302],
         [ -5.0759],
         [ -7.2463],
         [-10.8361],
         [-16.2457],
         [-17.9977],
         [-23.0035],
         [-24.1271]], grad_fn=<AddBackward0>),
 tensor([0., 1., 2., 3., 4., 5., 6., 7.]))

In [8]:
# Loss!
y_hat = my_model.foward(X)

my_model.loss(y, y_hat)

tensor(191.4239, grad_fn=<MeanBackward0>)

In [1]:
# Exercise: try to use other models (more entries) and another regression example

In [7]:
((0.3-1)**2/2 + (0.2-0)**2/2 + (0.8-1)**2/2)/3

0.09499999999999997